name: Sync to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Push to GitLab
      env:
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "60892406"
      run: |
        git config --global user.email "github-action@example.com"
        git config --global user.name "GitHub Action"
        git remote add gitlab https://gitlab.com/jevelasco5/Gluco_Fit.git
        git push gitlab main:main --force
